config/routes.rb
OoorTest::Application.routes.draw do
  resources :products

  resources :partners

  resources :open_erps

end

app/models/partner.rb
class Partner < ActiveRecord::Base
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  
  # GET /partners
  # GET /partners.json
  def index
    @partner = ResPartner.create(
      name: 'balls'
    )

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @partner }
    end
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
    @partner = ResPartner.find(:all, :domain=>[['ref', '=', "h_" + params[:id]]])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @partner }
    end
  end

  # GET /partners/new
  # GET /partners/new.json
  def new
    @partner = Partner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @partner }
    end
  end

  # GET /partners/1/edit
  def edit
    @partner = Partner.find(params[:id])
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = ResPartner.create(
      name: params[:name],
      ref: params[:ref],
      supplier: 'true',
      company_id: 3,
      property_account_receivable: 142,
      property_account_payable: 150
    )
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @partner }
      end
  end

  # PUT /partners/1
  # PUT /partners/1.json
  def update
    @partner = Partner.find(params[:id])

    respond_to do |format|
      if @partner.update_attributes(params[:partner])
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner = Partner.find(params[:id])
    @partner.destroy

    respond_to do |format|
      format.html { redirect_to partners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_form.html.erb
<%= form_for(@partner) do |f| %>
  <% if @partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
      <% @partner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :erp_id %><br />
    <%= f.number_field :erp_id %>
  </div>
  <div class="field">
    <%= f.label :hick_id %><br />
    <%= f.number_field :hick_id %>
  </div>
  <div class="field">
    <%= f.label :spree_id %><br />
    <%= f.number_field :spree_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partners/edit.html.erb
<h1>Editing partner</h1>

<%= render 'form' %>

<%= link_to 'Show', @partner %> |
<%= link_to 'Back', partners_path %>

app/views/partners/index.html.erb
<h1>Listing partners</h1>

<table>
  <tr>
    <th>Erp</th>
    <th>Hick</th>
    <th>Spree</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @partners.each do |partner| %>
  <tr>
    <td><%= partner.erp_id %></td>
    <td><%= partner.hick_id %></td>
    <td><%= partner.spree_id %></td>
    <td><%= link_to 'Show', partner %></td>
    <td><%= link_to 'Edit', edit_partner_path(partner) %></td>
    <td><%= link_to 'Destroy', partner, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Partner', new_partner_path %>

app/views/partners/new.html.erb
<h1>New partner</h1>

<%= render 'form' %>

<%= link_to 'Back', partners_path %>

app/views/partners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Erp:</b>
  <%= @partner.erp_id %>
</p>

<p>
  <b>Hick:</b>
  <%= @partner.hick_id %>
</p>

<p>
  <b>Spree:</b>
  <%= @partner.spree_id %>
</p>


<%= link_to 'Edit', edit_partner_path(@partner) %> |
<%= link_to 'Back', partners_path %>