config/routes.rb
OoorTest::Application.routes.draw do
  resources :products

  resources :partners

  resources :open_erps

end

app/models/open_erp.rb
class OpenErp < ActiveRecord::Base
end

app/controllers/open_erps_controller.rb
class OpenErpsController < ApplicationController
  # GET /open_erps
  # GET /open_erps.json
  def index
    @open_erps = ProductProduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @open_erps }
    end
  end

  # GET /open_erps/1
  # GET /open_erps/1.json
  def show
    @open_erp = OpenErp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @open_erp }
    end
  end

  # GET /open_erps/new
  # GET /open_erps/new.json
  def new
    @open_erp = OpenErp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @open_erp }
    end
  end

  # GET /open_erps/1/edit
  def edit
    @open_erp = OpenErp.find(params[:id])
  end

  # POST /open_erps
  # POST /open_erps.json
  def create
    @open_erp = OpenErp.new(params[:open_erp])

    respond_to do |format|
      if @open_erp.save
        format.html { redirect_to @open_erp, notice: 'Open erp was successfully created.' }
        format.json { render json: @open_erp, status: :created, location: @open_erp }
      else
        format.html { render action: "new" }
        format.json { render json: @open_erp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /open_erps/1
  # PUT /open_erps/1.json
  def update
    @open_erp = OpenErp.find(params[:id])

    respond_to do |format|
      if @open_erp.update_attributes(params[:open_erp])
        format.html { redirect_to @open_erp, notice: 'Open erp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @open_erp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /open_erps/1
  # DELETE /open_erps/1.json
  def destroy
    @open_erp = OpenErp.find(params[:id])
    @open_erp.destroy

    respond_to do |format|
      format.html { redirect_to open_erps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/open_erps_helper.rb
module OpenErpsHelper
end

app/views/open_erps/_form.html.erb
<%= form_for(@open_erp) do |f| %>
  <% if @open_erp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@open_erp.errors.count, "error") %> prohibited this open_erp from being saved:</h2>

      <ul>
      <% @open_erp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/open_erps/edit.html.erb
<h1>Editing open_erp</h1>

<%= render 'form' %>

<%= link_to 'Show', @open_erp %> |
<%= link_to 'Back', open_erps_path %>

app/views/open_erps/index.html.erb
<h1>Listing open_erps</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @open_erps.each do |open_erp| %>
  <tr>
    <td><%= link_to 'Show', open_erp %></td>
    <td><%= link_to 'Edit', edit_open_erp_path(open_erp) %></td>
    <td><%= link_to 'Destroy', open_erp, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Open erp', new_open_erp_path %>

app/views/open_erps/new.html.erb
<h1>New open_erp</h1>

<%= render 'form' %>

<%= link_to 'Back', open_erps_path %>

app/views/open_erps/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_open_erp_path(@open_erp) %> |
<%= link_to 'Back', open_erps_path %>